apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/component: root
    app.kubernetes.io/managed-by: argocd
  finalizers:
  - resources-finalizers.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/aditya3340/devops-essentials.git
    targetRevision: dev
    path: ./production-projects/app/
    directory:
      recurse: true
      include: |
        services/*.yaml
        monitoring/apps/*.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Prune=true
    - CreateNamespace=true