# production-projects/app/argo-apps/apps/loki-stack.yaml (Corrected for Local Chart)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/aditya3340/devops-essentials
    targetRevision: dev 
    path: production-projects/app/argo-apps/charts/loki-stack 
    
    helm:
      valueFiles:
        - values.yaml
      
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true