apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -vz postgres-service.fastapi.svc.cluster.local 5432; do echo waiting for db; sleep 2; done;' ]
      containers:
        - name: backend
          image: my-python-app:v1
          env:
          - name: POSTGRES_HOST
            value: "postgres-service.fastapi.svc.cluster.local"
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-db
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: fastapi
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
