# monitoring/apps/loki-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    path: ./production-projects/app/argo-apps/charts/frontend
    repoURL: https://github.com/aditya3340/devops-essentials/
    targetRevision: 2.10.3

    chart: loki-stack
    helm:
      valueFiles:
        - ./loki-stack-values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true